title:        BaoJy
tagline:      'Baojy , A College Student'
description:  'Welcom to my blog, if you like these, you can find me on twitter:<a href="https://twitter.com/BJY9" target="_blank">@BJY9</a>.'
url:          http://baojy.github.com
version:      1.1.1
author:
  name:       'BaoJy'
  email:      'baojy1993@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
